DROP TABLE ASESOR CASCADE CONSTRAINTS;
DROP TABLE TECNICO CASCADE CONSTRAINTS;
DROP TABLE LLAMADA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE AVERIA CASCADE CONSTRAINTS;
DROP TABLE DIRECCION CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE AGENDAR CASCADE CONSTRAINTS;
DROP TABLE ATENDER CASCADE CONSTRAINTS;
DROP TABLE GESTIONAR CASCADE CONSTRAINTS;
DROP TABLE REALIZAR CASCADE CONSTRAINTS;
DROP TABLE PERTENECER CASCADE CONSTRAINTS;

CREATE TABLE ASESOR(
DNI_ASESOR VARCHAR2(8) PRIMARY KEY,
CORREO_EMPRESA VARCHAR2(30),
CELULAR NUMBER(9), 
NOMBRE VARCHAR2(50),
USUARIO VARCHAR2(15),
CONTRASEÑA VARCHAR2(15)
);
select * from asesor;




CREATE TABLE TECNICO(
DNI_TECNICO VARCHAR2(8) PRIMARY KEY,
NOMBRE VARCHAR2(50),
CELULAR NUMBER(9),
COMPAÑIA VARCHAR2(30),
ESPECIALIZACION VARCHAR2(30)
);
select * from tecnico;

CREATE TABLE AGENDAR (
DISPONIBILIDAD VARCHAR2(10),
DNI_ASESOR REFERENCES ASESOR,
DNI_TECNICO REFERENCES TECNICO
);

select * from agendar;

CREATE TABLE USUARIO(
DNI_USUARIO NUMBER (8) PRIMARY KEY,
NOMBRE VARCHAR2(50),
TELEFONO NUMBER(9),
CORREO VARCHAR2(50),
SEGMENTO_SOCIAL VARCHAR2(15),
CODIGO_CLIENTE VARCHAR2(20)
);
select * from usuario;

CREATE TABLE AVERIA (
CODIGO_AVERIA VARCHAR2 (12) PRIMARY KEY,
HORA_LLEGADA VARCHAR2(20),
FECHA_INICIA DATE,
FECHA_FIN DATE,
ESTADO_AVERIA VARCHAR2(12),
DNI_ASESOR REFERENCES ASESOR,
DNI_USUARIO REFERENCES USUARIO
);
select * from averia;

CREATE TABLE ATENDER(
DNI_TECNICO REFERENCES TECNICO ,
CODIGO_AVERIA REFERENCES AVERIA,
HORA_SALIDA VARCHAR2(20),
HORA_LLEGADA VARCHAR2(20),
PRIMARY KEY (DNI_TECNICO,CODIGO_AVERIA)
);
select * from atender;


CREATE TABLE LLAMADA (
CONNID NUMBER(10) PRIMARY KEY,
INICIO_LLAMADA VARCHAR2(20),
FIN_LLAMADA VARCHAR2(20),
ESTADO_LLAMADA VARCHAR2(15),
ANI NUMBER(25)
);
select * from llamada;

CREATE TABLE GESTIONAR(
CONNID REFERENCES LLAMADA,
DNI_ASESOR REFERENCES ASESOR
);
select * from gestionar;

CREATE TABLE SERVICIO(
CODIGO_SERVICIO NUMBER(10) PRIMARY KEY,
TECNOLOGIA VARCHAR2(15),
ESTADO VARCHAR2(15),
EQUIPO VARCHAR2(30),
FECHA_INICIO DATE,
TIPO_PAQUETE VARCHAR2(20),
CICLO_FACTURACION VARCHAR2(20),
CODIGO_AVERIA REFERENCES AVERIA
);
select * from servicio;

CREATE TABLE REPARAR (
DNI_TECNICO REFERENCES TECNICO,
CODIGO_SERVICIO REFERENCES SERVICIO,
TROBA VARCHAR2(15),
NODO VARCHAR2(20)
);
select * from reparar;

CREATE TABLE DIRECCION(
CODIGO_DIREC VARCHAR2(100) PRIMARY KEY,
DEPARTAMENTO VARCHAR2(100),
PROVINCIA VARCHAR2(100),
CALLE VARCHAR2(100),
DISTRITO VARCHAR2(100),
URBANZIACION VARCHAR2(100),
MZ VARCHAR2(5),
LOTE VARCHAR2(5),
CODIGO_SERVICIO REFERENCES SERVICIO
);
select * from direccion;

CREATE TABLE REALIZAR(
DNI_USUARIO REFERENCES USUARIO,
CONNID REFERENCES LLAMADA
);
select * from realizar;

CREATE TABLE PERTENECER(
CODIGO_SERVICIO REFERENCES SERVICIO,
DNI_USUARIO REFERENCES USUARIO,
AVERIA_PENDIENTE VARCHAR2(30)
);
select * from pertenecer;

